# Application configuration for the API Gateway
server:
  port: 9000
  address: 0.0.0.0

# Spring application settings
spring:
  application:
    name: api-gateway

  # OAuth2 Resource Server configuration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

# Servers configuration
api-gateway:
  url: ${API_GATEWAY_URL:http://localhost:9000}
servers:
  client:
    uri: ${CLIENT_URL:http://localhost:3000}
  user-service:
    uri: ${USER_SERVICE_URL:http://localhost:8081}
  asset-service:
    uri: ${ASSET_SERVICE_URL:http://localhost:8080}
  mission-service:
    uri: ${MISSION_SERVICE_URL:http://localhost:8082}
  maintenance-service:
    uri: ${MAINTENANCE_SERVICE_URL:http://localhost:8084}

# OpenAPI documentation settings
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    urls:
      - name: Gateway
        url: /api-docs
      - name: Asset Service
        url: /aggregate/asset-service/api-docs
      - name: User Service
        url: /aggregate/user-service/api-docs
      - name: Mission Service
        url: /aggregate/mission-service/api-docs
      - name: Maintenance Service
        url: /aggregate/maintenance-service/api-docs