# Application configuration for the API Gateway
server:
  port: 9000

# Spring application settings
spring:
  application:
    name: api-gateway

  # OAuth2 Resource Server configuration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI}

# Servers configuration
servers:
  client:
    uri: ${CLIENT_URL:http://localhost:3000}
  asset-service:
    uri: ${ASSET_SERVICE_URL:http://localhost:8080}


# Role-Based Access Control (RBAC) settings
rbac:
  routes:
    - path: /api/assets/**
      methods: POST
      roles:
        - PILOT


# OpenAPI documentation settings
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    urls:
      - name: Asset Service
        url: /aggregate/asset-service/api-docs